// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myzdvvfhthqdfqousxpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15emR2dmZodGhxZGZxb3VzeHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDQ5NTEsImV4cCI6MjA3MjIyMDk1MX0.J61wQMmEF-UIs6r5Z2ajFbDVUTj6TKgviBv5GRfHojo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});